export const options = {
    'All': { label: '所有地區', value: 'All' },
    'Taipei': { label: '臺北市', value: 'Taipei' },
    'NewTaipei': { label: '新北市', value: 'NewTaipei' },
    'Taoyuan': { label: '桃園市', value: 'Taoyuan' },
    'Taichung': { label: '臺中市', value: 'Taichung' },
    'Tainan': { label: '臺南市', value: 'Tainan' },
    'Kaohsiung': { label: '高雄市', value: 'Kaohsiung' },
    'Keelung': { label: '基隆市', value: 'Keelung' },
    'Hsinchu': { label: '新竹市', value: 'Hsinchu' },
    'HsinchuCounty': { label: '新竹縣', value: 'HsinchuCounty' },
    'MiaoliCounty': { label: '苗栗縣', value: 'MiaoliCounty' },
    'ChanghuaCounty': { label: '彰化縣', value: 'ChanghuaCounty' },
    'NantouCounty': { label: '南投縣', value: 'NantouCounty' },
    'YunlinCounty': { label: '雲林縣', value: 'YunlinCounty' },
    'ChiayiCounty': { label: '嘉義縣', value: 'ChiayiCounty' },
    'Chiayi': { label: '嘉義市', value: 'Chiayi' },
    'PingtungCounty': { label: '屏東縣', value: 'PingtungCounty' },
    'YilanCounty': { label: '宜蘭縣', value: 'YilanCounty' },
    'HualienCounty': { label: '花蓮縣', value: 'HualienCounty' },
    'TaitungCounty': { label: '臺東縣', value: 'TaitungCounty' },
    'KinmenCounty': { label: '金門縣', value: 'KinmenCounty' },
    'PenghuCounty': { label: '澎湖縣', value: 'PenghuCounty' },
    'LienchiangCounty': { label: '連江縣', value: 'LienchiangCounty' }
};